apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: wordpress-pv 
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/wordpress/data