apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: wordpress
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      securityContext:
        runAsUser: 0000  # Replace with YOUR wordpress user's UID
        fsGroup: 0000   # Replace with YOUR wordpress user's GID
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 100m 
              memory: 128Mi
            limits:
              cpu: 500m 
              memory: 512Mi 
          env: 
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: mysql-secret
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: username 
                name: mysql-secret
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: mysql-secret
          - name: MYSQL_DATABASE
            value: wordpress
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-mysql-pvc
    