apiVersion: v1 
kind: PersistentVolume
metadata:
  name: wordpress-mysql-pv
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteOnce 
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain 
  hostPath:
    path: /home/wordpress/mysql
    