apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: wordpress-mysql-pvc
  namespace: wordpress
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard 
  accessModes:
    - ReadWriteOnce