apiVersion: v1 
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress
type: Opaque
data: 
  username: "YWRtaW4=" #You must change the username
  password: "TXlKZW5raW5zMTIzIQ==" #You must change the password